### ISSUE TITLE
Record some kind of expiration metric for cached errors

### ISSUE THREAD

**Issue by yhahn** [mapbox/tilelive-redis#23]
Prompted by discussion with @ianshward, on very quick read it seems like 403/404/500s atm have no way of benefitting from our stale object handling because they don't have enough metadata. This would make 403/404 objects to S3 possibly more latent than well-cached objects as we always have to go back to S3 to learn they don't exist.

- [x] Reread/add test to confirm/deny whether this is true
- [x] Fix

cc @ianshward @mapbox/platform

**Comment by ianshward** [comment]
I've got a fix going over in https://github.com/mapbox/tilelive-redis/pull/24

**Comment by ianshward** [comment]
Fixed in https://github.com/mapbox/tilelive-redis/pull/24
