### ISSUE TITLE
Needs better readme

### ISSUE THREAD

**Issue by tmcw** [mapbox/tilelive-redis#4]
From context knowledge (what redis does) I'm guessing that this is an in-between server that does caching. If so we should say that more explicitly in the readme.

**Comment by yhahn** [comment]
:point_up: @tmcw let me know what else would be helpful context here, other than a real readme for node-tilejson per https://github.com/mapbox/node-tilejson/issues/38.

**Comment by tmcw** [comment]
:+1: edit looks great.
